name: Laravel

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  laravel:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '8.1'
          extensions: mbstring, dom, fileinfo
          coverage: xdebug #optional
      - uses: getong/mariadb-action@v1.1
        with:
          host port: 3308 # Optional, default value is 3306. The port of host
          mariadb version: '10.3' # Optional, default value is "latest". The version of the MariaDB
          mysql database: 'testbench' # Optional, default value is "test". The specified database which will be create
          mysql user: 'default' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: 'secret' # Required if "mysql user" exists. The password for the "mysql user"
      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.1.0
        with:
          # Redis version to use
          redis-version: 6 # optional, default is latest, was 5
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run test & coverage
        run: vendor/bin/pest --coverage --ci --min=85
